# Generated by Django 5.0rc1 on 2024-10-13 18:03

import django.db.models.deletion
import notes.helpers.model
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_description_alter_picture_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='note',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='note',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user_modified',
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to=notes.helpers.model.PathAndRename.wrapper),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Izveidots')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Labots')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_note', to=settings.AUTH_USER_MODEL, verbose_name='Lietotājs izveidoja')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modified_note', to=settings.AUTH_USER_MODEL, verbose_name='Lietotājs laboja')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.info'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Title')),
                ('archive', models.BooleanField(default=False, verbose_name='Archive')),
                ('info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.info')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
