# Generated by Django 5.0rc1 on 2024-10-15 20:56

import django.db.models.deletion
import notes.helpers.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_tags_alter_picture_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='description_en',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='title_en',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='description_lv',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='title_lv',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='user_modified',
        ),
        migrations.AddField(
            model_name='note',
            name='public_link',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Public Url'),
        ),
        migrations.AddField(
            model_name='picture',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.info'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to=notes.helpers.model.PathAndRename.wrapper),
        ),
    ]
