# Generated by Django 5.0rc1 on 2024-11-20 20:34

import django.db.models.deletion
import notes.helpers.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_description_en_picture_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to=notes.helpers.model.PathAndRename.wrapper),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('header', 'Header'), ('paragraph', 'Paragraph')], max_length=20)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('level', models.SmallIntegerField(blank=True, null=True)),
                ('info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.info')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
