# Generated by Django 5.0rc1 on 2024-11-21 14:22

import notes.helpers.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_picture_content_type_alter_picture_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_tmp',
            field=models.BooleanField(default=False, verbose_name='Temporary image'),
        ),
        migrations.AddField(
            model_name='picture',
            name='session_key',
            field=models.CharField(blank=True, max_length=64, verbose_name='Session key'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to=notes.helpers.model.PathAndRename.wrapper),
        ),
    ]
