# Generated by Django 5.0rc1 on 2024-11-21 14:39

import notes.helpers.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_picture_is_tmp_picture_session_key_alter_picture_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='type',
            field=models.CharField(choices=[('default', 'default'), ('for_url', 'for_url')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to=notes.helpers.model.PathAndRename.wrapper),
        ),
    ]
