# Generated by Django 5.0rc1 on 2024-11-21 17:39

import notes.helpers.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_block_note_alter_picture_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to=notes.helpers.model.PathAndRename.wrapper),
        ),
    ]
