# Generated by Django 5.0rc1 on 2024-11-21 19:49

import notes.helpers.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_picture_height_picture_size_picture_width_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('header', 'Header'), ('paragraph', 'Paragraph'), ('linkTool', 'LinkTool')], max_length=20),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to=notes.helpers.model.PathAndRename.wrapper),
        ),
        migrations.AlterField(
            model_name='picture',
            name='session_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Session key'),
        ),
    ]
