# Generated by Django 5.0rc1 on 2024-03-25 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Title')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Izveidots')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Labots')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_vault', to=settings.AUTH_USER_MODEL, verbose_name='Lietotājs izveidoja')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modified_vault', to=settings.AUTH_USER_MODEL, verbose_name='Lietotājs laboja')),
            ],
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('value', models.TextField(blank=True, verbose_name='Data')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Izveidots')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Labots')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_treasure', to=settings.AUTH_USER_MODEL, verbose_name='Lietotājs izveidoja')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modified_treasure', to=settings.AUTH_USER_MODEL, verbose_name='Lietotājs laboja')),
                ('vault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.vault')),
            ],
        ),
    ]
